# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Provider-HTTP
version:      0.01
version_from: lib/Template/Provider/HTTP.pm
installdirs:  site
requires:
    Cwd:                           0
    Data::Dumper:                  0
    File::Slurp:                   0
    LWP::UserAgent:                0
    Template:                      0
    Test::HTTP::Server::Simple:    0
    Test::More:                    0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
